import sqlite3
import datetime
from config import DB_FILE

DB_PATH = DB_FILE
SCHEMA_VERSION = 3


def _backup_before_migration() -> None:
    if not DB_PATH.exists() or DB_PATH.stat().st_size == 0:
        return
    with sqlite3.connect(str(DB_PATH)) as source:
        current_version = source.execute("PRAGMA user_version").fetchone()[0]
        if current_version >= SCHEMA_VERSION:
            return
        backup_dir = DB_PATH.parent / "backups"
        backup_dir.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = backup_dir / f"{DB_PATH.stem}_v{current_version}_{timestamp}.db"
        with sqlite3.connect(str(backup_path)) as destination:
            source.backup(destination)

def get_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH), timeout=30.0)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA busy_timeout = 30000")
    return conn

def init_db():
    # Make sure target directory exists
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    _backup_before_migration()
    with get_db() as conn:
        conn.execute("PRAGMA journal_mode = WAL")
        # Principal transcription history table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS transcriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filename TEXT NOT NULL,
            filepath TEXT,
            file_hash TEXT,
            text TEXT NOT NULL,
            segments_json TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)
        
        # Migration: check and add filepath column if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN filepath TEXT")
        except sqlite3.OperationalError:
            # Column already exists
            pass

        # Migration: check and add file_hash column if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN file_hash TEXT")
        except sqlite3.OperationalError:
            # Column already exists
            pass
        
        # SQLite storage for chunks and embeddings
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER,
            text TEXT NOT NULL,
            embedding BLOB NOT NULL,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)
        
        # Summaries generated by the LLM
        conn.execute("""
        CREATE TABLE IF NOT EXISTS summaries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER UNIQUE,
            text TEXT NOT NULL,
            mode TEXT DEFAULT 'meeting',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)

        # Migration: check and add mode column if not present in existing summaries table
        try:
            conn.execute("ALTER TABLE summaries ADD COLUMN mode TEXT DEFAULT 'meeting'")
        except sqlite3.OperationalError:
            # Column already exists
            pass
        
        # Chat Q&A history per transcription
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER,
            role TEXT NOT NULL, -- 'user' or 'assistant'
            text TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)

        # Projects table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Folders table (supports nested subfolders via parent_id)
        conn.execute("""
        CREATE TABLE IF NOT EXISTS folders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_id INTEGER NOT NULL,
            parent_id INTEGER,
            name TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(parent_id) REFERENCES folders(id) ON DELETE CASCADE
        )
        """)

        # Migration: check and add project_id column to transcriptions if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL")
        except sqlite3.OperationalError:
            pass

        # Migration: check and add folder_id column to transcriptions if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN folder_id INTEGER REFERENCES folders(id) ON DELETE SET NULL")
        except sqlite3.OperationalError:
            pass

        # Chat Sessions table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_sessions (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            context_sources TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Migration: check and add session_id column to chat_history if not present
        try:
            conn.execute("ALTER TABLE chat_history ADD COLUMN session_id TEXT REFERENCES chat_sessions(id) ON DELETE CASCADE")
        except sqlite3.OperationalError:
            pass

        # Required by current chat queries. This migration must also exist for
        # databases created from scratch, not only for historical installations.
        try:
            conn.execute("ALTER TABLE chat_history ADD COLUMN context_sources TEXT")
        except sqlite3.OperationalError:
            pass

        # Migration: add metadata columns for web_sources, citations, search_logs
        for col in [
            "web_sources_json TEXT",
            "citations_json TEXT",
            "search_logs_json TEXT"
        ]:
            try:
                conn.execute(f"ALTER TABLE chat_history ADD COLUMN {col}")
            except sqlite3.OperationalError:
                pass

        # Notebook Notes table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS notes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            source_type TEXT DEFAULT 'user_note',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Persistent state for background operations. Existing endpoints remain
        # compatible while clients can optionally inspect individual jobs.
        conn.execute("""
        CREATE TABLE IF NOT EXISTS jobs (
            id TEXT PRIMARY KEY,
            kind TEXT NOT NULL,
            resource_id INTEGER,
            status TEXT NOT NULL,
            progress INTEGER DEFAULT 0,
            message TEXT,
            error TEXT,
            payload_json TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            started_at TIMESTAMP,
            finished_at TIMESTAMP
        )
        """)
        try:
            conn.execute("ALTER TABLE jobs ADD COLUMN payload_json TEXT")
        except sqlite3.OperationalError:
            pass

        # Index/version metadata makes embedding compatibility explicit while
        # keeping all existing vectors readable.
        for col in [
            "embedding_model TEXT",
            "embedding_dimension INTEGER",
            "index_version INTEGER DEFAULT 1"
        ]:
            try:
                conn.execute(f"ALTER TABLE chunks ADD COLUMN {col}")
            except sqlite3.OperationalError:
                pass

        conn.execute("CREATE INDEX IF NOT EXISTS idx_chunks_transcription_id ON chunks(transcription_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_transcriptions_file_hash ON transcriptions(file_hash)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_transcriptions_project_id ON transcriptions(project_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_transcriptions_folder_id ON transcriptions(folder_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_folders_project_id ON folders(project_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_folders_parent_id ON folders(parent_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_chat_history_session_id ON chat_history(session_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_jobs_resource ON jobs(kind, resource_id, status)")

        conn.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")
        conn.commit()
