import sqlite3
import json
import pickle
from pathlib import Path
from typing import List, Dict, Any, Tuple
from config import settings

DB_PATH = Path(__file__).parent.parent / "data" / "database.db"

def get_db():
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn

def init_db():
    # Make sure target directory exists
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    with get_db() as conn:
        # Principal transcription history table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS transcriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filename TEXT NOT NULL,
            filepath TEXT,
            file_hash TEXT,
            text TEXT NOT NULL,
            segments_json TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)
        
        # Migration: check and add filepath column if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN filepath TEXT")
        except sqlite3.OperationalError:
            # Column already exists
            pass

        # Migration: check and add file_hash column if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN file_hash TEXT")
        except sqlite3.OperationalError:
            # Column already exists
            pass
        
        # SQLite storage for chunks and embeddings
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER,
            text TEXT NOT NULL,
            embedding BLOB NOT NULL,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)
        
        # Summaries generated by the LLM
        conn.execute("""
        CREATE TABLE IF NOT EXISTS summaries (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER UNIQUE,
            text TEXT NOT NULL,
            mode TEXT DEFAULT 'meeting',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)

        # Migration: check and add mode column if not present in existing summaries table
        try:
            conn.execute("ALTER TABLE summaries ADD COLUMN mode TEXT DEFAULT 'meeting'")
        except sqlite3.OperationalError:
            # Column already exists
            pass
        
        # Chat Q&A history per transcription
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_history (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            transcription_id INTEGER,
            role TEXT NOT NULL, -- 'user' or 'assistant'
            text TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(transcription_id) REFERENCES transcriptions(id) ON DELETE CASCADE
        )
        """)

        # Projects table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Folders table (supports nested subfolders via parent_id)
        conn.execute("""
        CREATE TABLE IF NOT EXISTS folders (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            project_id INTEGER NOT NULL,
            parent_id INTEGER,
            name TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
            FOREIGN KEY(parent_id) REFERENCES folders(id) ON DELETE CASCADE
        )
        """)

        # Migration: check and add project_id column to transcriptions if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN project_id INTEGER REFERENCES projects(id) ON DELETE SET NULL")
        except sqlite3.OperationalError:
            pass

        # Migration: check and add folder_id column to transcriptions if not present
        try:
            conn.execute("ALTER TABLE transcriptions ADD COLUMN folder_id INTEGER REFERENCES folders(id) ON DELETE SET NULL")
        except sqlite3.OperationalError:
            pass

        # Chat Sessions table
        conn.execute("""
        CREATE TABLE IF NOT EXISTS chat_sessions (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            context_sources TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """)

        # Migration: check and add session_id column to chat_history if not present
        try:
            conn.execute("ALTER TABLE chat_history ADD COLUMN session_id TEXT REFERENCES chat_sessions(id) ON DELETE CASCADE")
        except sqlite3.OperationalError:
            pass

        conn.commit()

init_db()
